In [9]:
import pandas as pd
import tensorflow as tf

dataframe = pd.read_csv("diabetes.csv")
dataframe.shape

(768, 9)

In [10]:
dataframe.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
val_dataframe = dataframe.sample(frac=0.2, random_state=1337)

In [4]:
train_dataset = dataframe.drop(val_dataframe.index)

In [5]:
print("Using %d samples for training and %d for validation" 
      % (len(train_dataset), len(val_dataframe)))

Using 614 samples for training and 154 for validation


In [6]:
def dataframe_to_dataset(dataframe):
    dataframe = dataframe.copy()
    labels = dataframe.pop("Outcome")
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    ds = ds.shuffle(buffer_size=len(dataframe))
    return ds

In [17]:
dict(train_dataset)

{'Pregnancies': 0       6
 1       1
 4       0
 5       5
 6       3
        ..
 762     9
 763    10
 764     2
 765     5
 766     1
 Name: Pregnancies, Length: 614, dtype: int64,
 'Glucose': 0      148
 1       85
 4      137
 5      116
 6       78
       ... 
 762     89
 763    101
 764    122
 765    121
 766    126
 Name: Glucose, Length: 614, dtype: int64,
 'BloodPressure': 0      72
 1      66
 4      40
 5      74
 6      50
        ..
 762    62
 763    76
 764    70
 765    72
 766    60
 Name: BloodPressure, Length: 614, dtype: int64,
 'SkinThickness': 0      35
 1      29
 4      35
 5       0
 6      32
        ..
 762     0
 763    48
 764    27
 765    23
 766     0
 Name: SkinThickness, Length: 614, dtype: int64,
 'Insulin': 0        0
 1        0
 4      168
 5        0
 6       88
       ... 
 762      0
 763    180
 764      0
 765    112
 766      0
 Name: Insulin, Length: 614, dtype: int64,
 'BMI': 0      33.6
 1      26.6
 4      43.1
 5      25.6
 6      31.0

In [14]:
train_ds = dataframe_to_dataset(train_dataset)

In [12]:
val_ds = dataframe_to_dataset(val_dataframe)

In [13]:
for x,y in train_ds.take(1):
    print("Input:", x)
    print("Target:", y)

Input: {'Pregnancies': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'Glucose': <tf.Tensor: shape=(), dtype=int64, numpy=127>, 'BloodPressure': <tf.Tensor: shape=(), dtype=int64, numpy=46>, 'SkinThickness': <tf.Tensor: shape=(), dtype=int64, numpy=21>, 'Insulin': <tf.Tensor: shape=(), dtype=int64, numpy=335>, 'BMI': <tf.Tensor: shape=(), dtype=float64, numpy=34.4>, 'DiabetesPedigreeFunction': <tf.Tensor: shape=(), dtype=float64, numpy=0.176>, 'Age': <tf.Tensor: shape=(), dtype=int64, numpy=22>}
Target: tf.Tensor(0, shape=(), dtype=int64)
